export const WORDS = [
    // Biblia
    "Adão",
    "Eva",
    "Noé",
    "Abraão",
    "Jacó",
    "Esaú",
    "Moisés",
    "Sansão",
    "Rei Davi",
    "Golias",
    "Salomão",
    "Elias",
    "Mula de Balaão",
    "Isaías",
    "Jeremias",
    "Ezequiel",
    "Daniel",
    "Sadraque",
    "Mesaque",
    "Abede-Nego",
    "Ester",
    "Mardoqueu",
    "Neemias",
    "Jó",
    "Jonas",
    "João Batista",
    "Maria Madalena",
    "Jesus",
    "Pedro (Simão)",
    "João",
    "Bartolomeu",
    "Tomé",
    "Mateus",
    "Judas Iscariotes",
    "Paulo",
    "Barnabé",
    "Herodes",
    "Pilatos",
    "Nicodemos",
    "Livro de Romanos",
    "Livro de Apocalipse",
    "Livro de Genesis",
    "Livro de Salmos",
    "Livro de Atos",
    "Evangelho de João",
    "Evangelho de Mateus",
    "Livro de Tiago",
    "Carta aos Efésios",
    "Livro de Gálatas",
    "Livro de Filipenses",

    // 🐾 Animais
    "elefante",
    "girafa",
    "pinguim",
    "leão",
    "tigre",
    "cobra",
    "polvo",
    "tubarão",
    "coruja",
    "flamingo",
    "ornitorrinco",
    "camelo",
    "gorila",
    "rinoceronte",
    "hipopótamo",
    "avestruz",
    "papagaio",
    "canguru",
    "panda",
    "lobo",
    "raposa",
    "urso",

    // 🍕 Comida & Bebida
    "pizza",
    "sushi",
    "hambúrguer",
    "lasanha",
    "brigadeiro",
    "sorvete",
    "macarrão",
    "frango",
    "pipoca",
    "bolo de cenoura",
    "tapioca",
    "açaí",
    "churrasco",
    "coxinha",
    "pastel",
    "pudim",
    "yakisoba",
    "caldo de cana",
    "pão de queijo",
    "feijoada",

    // 🎬 Filmes & Séries
    "Titanic",
    "Avatar",
    "Vingadores",
    "Homem-Aranha",
    "Batman",
    "Superman",
    "Coringa",
    "Interestelar",
    "Matrix",
    "Jurassic Park",
    "O Rei Leão",
    "Toy Story",
    "Shrek",
    "Frozen",
    "Procurando Nemo",
    "Os Incríveis",
    "Carros",
    "Up",
    "Ratatouille",
    "Wall-E",
    "Monstros S.A.",
    "Moana",
    "Aladdin",
    "Hércules",
    "Tarzan",
    "Mulan",
    "Enrolados",
    "A Bela e a Fera",
    "Branca de Neve",
    "Cinderela",
    "O Poderoso Chefão",
    "Clube da Luta",
    "Forrest Gump",
    "O Senhor dos Anéis",
    "Harry Potter",
    "Star Wars",
    "Piratas do Caribe",
    "Indiana Jones",
    "De Volta para o Futuro",
    "E.T.",
    "Rocky",
    "Rambo",
    "Gladiador",
    "Troia",
    "300",
    "Oppenheimer",
    "Barbie",
    "Deadpool",
    "Pantera Negra",
    "Homem de Ferro",
    "Thor",
    "Hulk",
    "Capitão América",
    "Guardiões da Galáxia",
    "Doutor Estranho",
    "Homem-Formiga",
    "Viúva Negra",
    "Flash",
    "Aquaman",
    "Mulher-Maravilha",
    "Shazam!",
    "It: A Coisa",
    "Invocação do Mal",
    "Annabelle",
    "Pânico",
    "Jogos Mortais",
    "O Exorcista",
    "Sexta-Feira 13",
    "A Freira",
    "Um Lugar Silencioso",
    "O Iluminado",
    "Interestelar",
    "Gravidade",
    "O Náufrago",
    "A Origem",
    "O Show de Truman",
    "O Máskara",
    "Todo Mundo em Pânico",
    "As Branquelas",
    "Se Beber, Não Case",
    "Debi & Lóide",
    "Esqueceram de Mim",
    "Meninas Malvadas",
    "As Patricinhas de Beverly Hills",
    "Legalmente Loira",
    "O Diabo Veste Prada",
    "Crepúsculo",
    "Jogos Vorazes",
    "Divergente",
    "Maze Runner",
    "John Wick",
    "Missão Impossível",
    "Velozes e Furiosos",
    "Transformers",
    "Godzilla",
    "King Kong",
    "O Máskara",
    "Click",
    "Jumanji",

    // 🏠 Objetos do dia a dia
    "abridor de garrafa",
    "descascador de legumes",
    "espremedor de alho",
    "ralador de queijo",
    "saca-rolhas",
    "peneira",
    "funil",
    "pegador de macarrão",
    "escorredor de arroz",
    "tábua de cortar",
    "luva de forno",
    "medidor de cozinha",
    "forma de gelo",
    "pote hermético",
    "porta-temperos",
    "timer de cozinha",
    "mixer de mão",
    "liquidificador",
    "cafeteira",
    "sanduicheira",
    "controle remoto",
    "carregador de celular",
    "cabo USB",
    "adaptador de tomada",
    "filtro de linha",
    "extensão elétrica",
    "pen drive",
    "cartão de memória",
    "fone de ouvido",
    "caixa de som",
    "webcam",
    "mouse sem fio",
    "teclado mecânico",
    "mousepad",
    "suporte para celular",
    "tripé para celular",
    "ring light",
    "calculadora",
    "despertador digital",
    "pilha AA",
    "lanterna",
    "chave de fenda",
    "chave inglesa",
    "alicate",
    "trena",
    "martelo",
    "furadeira",
    "parafuso",
    "bucha de parede",
    "fita isolante",
    "fita adesiva",
    "cola quente",
    "pistola de cola quente",
    "estilete",
    "tesoura de poda",
    "regador",
    "vaso de plantas",
    "pá de jardinagem",
    "vassoura",
    "rodo",
    "pá de lixo",
    "esponja de louça",
    "escova de dentes",
    "fio dental",
    "cortador de unhas",
    "pinça",
    "pente",
    "escova de cabelo",
    "secador de cabelo",
    "barbeador elétrico",
    "espelho de mão",
    "cabide",
    "pregador de roupa",
    "varal de roupas",
    "ferro de passar",
    "tábua de passar",
    "cesto de roupa",
    "guarda-chuva",
    "chaveiro",
    "cadeado",
    "carteira",
    "porta-moedas",
    "óculos de sol",
    "relógio de pulso",
    "mochila",
    "estojo escolar",
    "grampeador",
    "furador de papel",
    "marca-texto",
    "corretivo",
    "post-it",
    "régua",
    "calculadora científica",
    "canivete",
    "garrafa térmica",
    "copo medidor",
    "saco a vácuo",
    "isqueiro",
    "vela aromática",

    // 🏙️ Lugares
    "praia",
    "floresta",
    "museu",
    "zoológico",
    "aeroporto",
    "supermercado",
    "biblioteca",
    "hospital",
    "estádio",
    "cinema",
    "parque de diversões",
    "castelo",
    "farol",
    "favelinha",
    "metrô",
    "posto de gasolina",
    "delegacia",
    "cartório",
    "feira livre",
    "escola",
    "universidade",
    "igreja",
    "shopping",
    "restaurante",
    "lanchonete",
    "padaria",
    "farmácia",
    "academia",
    "salão de beleza",
    "barbearia",
    "hotel",
    "pousada",
    "acampamento",
    "fazenda",
    "sítio",
    "chácara",
    "cachoeira",
    "rio",
    "lago",
    "montanha",
    "caverna",
    "ilha",
    "deserto",
    "vulcão",
    "geleira",
    "aquário",
    "planetário",
    "teatro",
    "circo",
    "boate",
    "praça",
    "parque",
    "playground",
    "quadra de futebol",
    "quadra de basquete",
    "piscina",
    "academia ao ar livre",
    "pista de skate",
    "pista de corrida",
    "autódromo",
    "rodoviária",
    "estação de trem",
    "estação de metrô",
    "porto",
    "marina",
    "ponte",
    "túnel",
    "estacionamento",
    "oficina mecânica",
    "borracharia",
    "lava-rápido",
    "banco",
    "correios",
    "prefeitura",
    "fórum",
    "tribunal",
    "cemitério",
    "prisão",
    "quartel",
    "corpo de bombeiros",
    "posto de saúde",
    "consultório médico",
    "clínica veterinária",
    "pet shop",
    "floricultura",
    "loja de roupas",
    "loja de brinquedos",
    "loja de eletrônicos",
    "papelaria",
    "livraria",
    "mercado municipal",
    "shopping center",
    "parque aquático",
    "resort",
    "mirante",
    "teleférico",
    "estação de esqui",
    "ruínas antigas",
    "sala de aula",
    "cozinha industrial",

    // 🎵 Música & Artistas
    "bateria",
    "saxofone",
    "gaita",
    "triângulo",
    "cavaquinho",
    "acordeon",
    "violoncelo",
    "tuba",
    "harpa",
    "theremin",
    "violão",
    "tuba",

    // 👔 Profissões
    "astronauta",
    "palhaço",
    "bombeiro",
    "detetive",
    "mágico",
    "espião",
    "pirata",
    "samurai",
    "faraó",
    "gladiador",
    "druida",
    "ninja",
    "cowboy",
    "domador de leões",
    "médico",
    "enfermeiro",
    "dentista",
    "veterinário",
    "professor",
    "advogado",
    "juiz",
    "policial",
    "soldado",
    "piloto",
    "comissário de bordo",
    "motorista",
    "motoboy",
    "carteiro",
    "cozinheiro",
    "garçom",
    "padeiro",
    "açougueiro",
    "confeiteiro",
    "barbeiro",
    "cabeleireiro",
    "maquiador",
    "fotógrafo",
    "cinegrafista",
    "jornalista",
    "repórter",
    "ator",
    "cantor",
    "dançarino",
    "músico",
    "ilustrador",
    "designer",
    "programador",
    "desenvolvedor de jogos",
    "engenheiro",
    "arquiteto",
    "eletricista",
    "encanador",
    "pedreiro",
    "pintor",
    "carpinteiro",
    "marceneiro",
    "mecânico",
    "ferreiro",
    "jardineiro",
    "agricultor",
    "pescador",
    "fazendeiro",
    "apicultor",
    "arqueólogo",
    "cientista",
    "biólogo",
    "astrônomo",
    "químico",
    "geólogo",
    "psicólogo",
    "terapeuta",
    "farmacêutico",
    "bibliotecário",
    "contador",
    "bancário",
    "vendedor",
    "corretor de imóveis",
    "empresário",
    "secretário",
    "recepcionista",
    "gerente",
    "fotomodelo",
    "estilista",
    "joalheiro",
    "relojoeiro",
    "sapateiro",
    "costureiro",
    "alfaiate",
    "massagista",
    "personal trainer",
    "instrutor de academia",
    "treinador de futebol",
    "árbitro",
    "juiz de futebol",
    "bailarino",
    "dublador",
    "dublê",
    "cascateiro",
    "guia turístico",
    "detetive particular",

    // 🌍 Natureza & Fenômenos
    "tsunami",
    "tornado",
    "eclipse",
    "aurora boreal",
    "vulcão",
    "avalanche",
    "trovoada",
    "maré alta",
    "nebulosa",
    "geyser",
    "terremoto",
    "furacão",
    "maremoto",
    "arco-íris",
    "tempestade",
    "raio",
    "relâmpago",
    "granizo",
    "nevasca",
    "geada",
    "chuva",
    "chuva de meteoros",
    "enchente",
    "seca",
    "deslizamento de terra",
    "erupção vulcânica",
    "terremoto submarino",
    "ondas gigantes",
    "redemoinho",
    "ciclone",
    "monção",
    "vendaval",
    "neblina",
    "nuvem de tempestade",
    "arco-íris duplo",
    "pôr do sol",
    "nascer do sol",
    "lua cheia",
    "lua crescente",
    "chuva de estrelas",
    "estrela cadente",
    "via láctea",
    "buraco negro",
    "supernova",
    "galáxia",
    "cometa",
    "asteroide",
    "meteoro",
    "satélite natural",
    "constelação",
    "oceano",
    "cachoeira",
    "rio",
    "lago",
    "lagoa",
    "córrego",
    "nascente",
    "caverna",
    "gruta",
    "penhasco",
    "montanha",
    "vulcão submarino",
    "geleira",
    "iceberg",
    "deserto",
    "duna",
    "floresta",
    "selva",
    "mata",
    "manguezal",
    "pântano",
    "pantanal",
    "cerrado",
    "caatinga",
    "campo de flores",
    "pradaria",
    "árvore",
    "cacto",
    "bambu",
    "cogumelo",
    "samambaia",
    "orquídea",
    "girassol",
    "lótus",
    "flor desabrochando",
    "folha caindo",
    "semente germinando",
    "ninho de pássaros",
    "teia de aranha",
    "formigueiro",
    "colmeia",
    "coral",
    "recife de coral",
    "cardume de peixes",
    "migração de aves",
    "canto dos pássaros",
    "pegada de animal",
    "pôr da lua",

    // 🚗 Transportes
    "carro",
    "ônibus",
    "caminhão",
    "moto",
    "bicicleta",
    "patinete",
    "skate",
    "trem",
    "metrô",
    "bonde",
    "VLT",
    "avião",
    "helicóptero",
    "jatinho",
    "dirigível",
    "balão",
    "paraquedas",
    "navio",
    "barco",
    "lancha",
    "iate",
    "veleiro",
    "canoa",
    "caiaque",
    "balsa",
    "submarino",
    "jet ski",
    "quadriciclo",
    "trator",
    "retroescavadeira",
    "empilhadeira",
    "ambulância",
    "viatura policial",
    "caminhão de bombeiros",
    "carro de corrida",
    "kart",
    "limusine",
    "táxi",
    "carro elétrico",
    "carro conversível",
    "carro antigo",
    "carroça",
    "charrete",
    "carruagem",
    "trenó",
    "teleférico",
    "funicular",
    "elevador",
    "escada rolante",
    "esteira rolante",
    "monotrilho",
    "trem-bala",
    "trem de carga",
    "trem turístico",
    "ônibus escolar",
    "ônibus articulado",
    "ônibus de viagem",
    "micro-ônibus",
    "van",
    "motorhome",
    "trailer",
    "furgão",
    "picape",
    "SUV",
    "limusine",
    "mototáxi",
    "triciclo",
    "triciclo elétrico",
    "bicicleta elétrica",
    "patinete elétrico",
    "monociclo",
    "hoverboard",
    "segway",
    "drone",
    "avião de caça",
    "avião agrícola",
    "avião de carga",
    "hidroavião",
    "ultraleve",
    "planador",
    "asa-delta",
    "parapente",
    "foguete",
    "nave espacial",
    "veículo lunar",
    "cargueiro",
    "navio de cruzeiro",
    "porta-aviões",
    "navio petroleiro",
    "navio pirata",
    "barco a remo",
    "gôndola",
    "bote salva-vidas",
    "prancha de surf",
    "jangada",
    "balão de ar quente",
    "trenó puxado por cães",

    // 🎪 Personagens fictícios & clássicos
    "Cinderela",
    "Pinóquio",
    "Peter Pan",
    "Chapeuzinho Vermelho",
    "Branca de Neve",
    "Alice no País das Maravilhas",
    "Polifemo",
    "Medusa",
    "Thor",
    "Batman",
    "Mulher-Maravilha",
    "Supergirl",
    "Superman",
    "Homem-Aranha",
    "Homem de Ferro",
    "Capitão América",
    "Hulk",
    "Homem-Formiga",
    "Pantera Negra",
    "Viúva Negra",
    "Doutor Estranho",
    "Flash",
    "Aquaman",
    "Coringa",
    "Arlequina",
    "Mulher-Gato",
    "Duende Verde",
    "Thanos",
    "Loki",
    "Deadpool",
    "Wolverine",
    "Mickey Mouse",
    "Minnie Mouse",
    "Pato Donald",
    "Pateta",
    "Pernalonga",
    "Tom",
    "Jerry",
    "Scooby-Doo",
    "Salsicha",
    "Bob Esponja",
    "Patrick Estrela",
    "Pica-Pau",
    "Popeye",
    "Garfield",
    "Homer Simpson",
    "Bart Simpson",
    "Shrek",
    "Burro",
    "Fiona",
    "Gato de Botas",
    "Woody",
    "Buzz Lightyear",
    "Nemo",
    "Dory",
    "Relâmpago McQueen",
    "Simba",
    "Scar",
    "Mufasa",
    "Timão",
    "Pumba",
    "Stitch",
    "Elsa",
    "Anna",
    "Olaf",
    "Maui",
    "Aladdin",
    "Jasmine",
    "Gênio",
    "Hércules",
    "Tarzan",
    "Mowgli",
    "Peter Parker",
    "Katniss Everdeen",
    "Harry Potter",
    "Hermione Granger",
    "Ron Weasley",
    "Darth Vader",
    "Luke Skywalker",
    "Yoda",
    "Chewbacca",
    "Indiana Jones",
    "Jack Sparrow",
    "Capitão Gancho",
    "Willy Wonka",
    "O Chapeleiro Maluco",
    "Rainha de Copas",
    "Sonic",
    "Mario",
    "Luigi",
    "Pac-Man",
    "Link",
    "Pikachu",
    "Ash Ketchum",
    "Goku",
    "Naruto",
    "Homer Simpson",
    "Gru",

    // 🏆 Esportes
    "vôlei de praia",
    "surfe",
    "ginástica olímpica",
    "luta livre",
    "tiro com arco",
    "hipismo",
    "esgrima",
    "cabo de guerra",
    "corrida de saco",
    "tênis de mesa",
    "badminton",
    "futebol",
    "futsal",
    "basquete",
    "beisebol",
    "softbol",
    "handebol",
    "rúgbi",
    "futebol americano",
    "críquete",
    "tênis",
    "golfe",
    "boxe",
    "muay thai",
    "karatê",
    "judô",
    "taekwondo",
    "jiu-jitsu",
    "wrestling",
    "MMA",
    "ciclismo",
    "mountain bike",
    "BMX",
    "skate",
    "patinação artística",
    "patinação de velocidade",
    "natação",
    "nado sincronizado",
    "polo aquático",
    "mergulho",
    "maratona",
    "corrida de obstáculos",
    "salto em distância",
    "salto em altura",
    "salto com vara",
    "arremesso de peso",
    "lançamento de dardo",
    "lançamento de disco",
    "lançamento de martelo",
    "triathlon",
    "pentatlo moderno",
    "decatlo",
    "levantamento de peso",
    "crossfit",
    "esqui",
    "esqui alpino",
    "snowboard",
    "curling",
    "hóquei no gelo",
    "hóquei sobre grama",
    "patinação no gelo",
    "bobsled",
    "luge",
    "skeleton",
    "escalada esportiva",
    "parkour",
    "skysurf",
    "paraquedismo",
    "parapente",
    "asa-delta",
    "vela",
    "remo",
    "canoagem",
    "caiaque",
    "rafting",
    "motocross",
    "Fórmula 1",
    "kart",
    "automobilismo",
    "motovelocidade",
    "tiro esportivo",
    "tiro ao prato",
    "boliche",
    "sinuca",
    "bilhar",
    "dardos",
    "peteca",
    "bocha",
    "croquet",
    "polo",
    "softbol",
    "frescobol",
    "wakesurf",
    "kitesurf",
    "windsurf",
    "bodyboard",
    "stand up paddle",
    "pesca esportiva",
    "xadrez",
    "damas",
];

function shuffleInPlace(arr) {
    for (let i = arr.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [arr[i], arr[j]] = [arr[j], arr[i]];
    }
    return arr;
}

export function getRandomWords(usedWords = [], n = 1) {
    const used = new Set(usedWords);
    const uniqueWords = [...new Set(WORDS)];

    let pool = uniqueWords.filter((w) => !used.has(w));
    if (pool.length === 0) pool = [...uniqueWords];

    shuffleInPlace(pool);

    const picked = [];
    const pickedSet = new Set();

    while (picked.length < n) {
        if (pool.length === 0) {
            pool = uniqueWords.filter((w) => !pickedSet.has(w));
            shuffleInPlace(pool);
            if (pool.length === 0) break;
        }
        const word = pool.pop();
        if (pickedSet.has(word)) continue;
        pickedSet.add(word);
        picked.push(word);
    }

    return picked;
}
