export const WORDS = [
    // 🐾 Animais
    "elefante",
    "girafa",
    "pinguim",
    "leão",
    "tigre",
    "cobra",
    "polvo",
    "tubarão",
    "coruja",
    "flamingo",
    "ornitorrinco",
    "camelo",
    "gorila",
    "rinoceronte",
    "hipopótamo",
    "avestruz",
    "papagaio",
    "canguru",
    "panda",
    "lobo",
    "raposa",
    "urso",

    // 🍕 Comida & Bebida
    "pizza",
    "sushi",
    "hambúrguer",
    "lasanha",
    "brigadeiro",
    "sorvete",
    "macarrão",
    "frango",
    "pipoca",
    "bolo de cenoura",
    "tapioca",
    "açaí",
    "churrasco",
    "coxinha",
    "pastel",
    "pudim",
    "yakisoba",
    "caldo de cana",
    "pão de queijo",
    "feijoada",

    // 🎬 Filmes & Séries
    "Titanic",
    "Matrix",
    "Interestelar",
    "Vingadores",
    "Toy Story",
    "O Rei Leão",
    "Harry Potter",
    "Star Wars",
    "A Casa de Papel",
    "Breaking Bad",
    "Stranger Things",
    "Round 6",
    "Friends",
    "Homem-Aranha",
    "Divertidamente",
    "Shrek",
    "Frozen",
    "Moana",

    // 🎮 Jogos & Entretenimento
    "Minecraft",
    "Fortnite",
    "xadrez",
    "dominó",
    "baralho",
    "boliche",
    "dança da cadeira",
    "cabo de guerra",
    "caça ao tesouro",
    "mímica",
    "stop",
    "amarelinha",
    "pular corda",

    // 🏠 Objetos do dia a dia
    "geladeira",
    "liquidificador",
    "guarda-chuva",
    "mochila",
    "espelho",
    "travesseiro",
    "lustre",
    "vassoura",
    "régua",
    "tesoura",
    "martelo",
    "lâmpada",
    "chave de fenda",
    "agenda",
    "cofre",
    "binóculo",
    "lanterna",
    "calendário",
    "termômetro",

    // 🏙️ Lugares
    "praia",
    "floresta",
    "museu",
    "zoológico",
    "aeroporto",
    "supermercado",
    "biblioteca",
    "hospital",
    "estádio",
    "cinema",
    "parque de diversões",
    "castelo",
    "farol",
    "favelinha",
    "metrô",
    "posto de gasolina",
    "delegacia",
    "cartório",
    "feira livre",

    // 🎭 Ações & Verbos
    "surfar",
    "esquiar",
    "meditar",
    "malabarismo",
    "patinar",
    "escalar",
    "mergulhar",
    "capoeira",
    "cambalhotar",
    "roncar",
    "caminhar na lua",
    "tocar violão",
    "fritar ovo",
    "dar carona",
    "tirar selfie",
    "perder o ônibus",
    "montar barraca",
    "fazer mágica",
    "consertar bicicleta",
    "plantar árvore",

    // 🎵 Música & Artistas
    "bateria",
    "saxofone",
    "gaita",
    "triângulo",
    "cavaquinho",
    "acordeon",
    "violoncelo",
    "tuba",
    "harpa",
    "theremin",

    // 👔 Profissões
    "astronauta",
    "palhaço",
    "bombeiro",
    "detetive",
    "mágico",
    "marionete",
    "espião",
    "pirata",
    "samurai",
    "faraó",
    "gladiador",
    "druida",
    "ninja",
    "cowboy",
    "domador de leões",

    // 🌍 Natureza & Fenômenos
    "tsunami",
    "tornado",
    "eclipse",
    "aurora boreal",
    "vulcão",
    "avalanche",
    "trovoada",
    "maré alta",
    "nebulosa",
    "geyser",

    // 🚗 Transportes
    "helicóptero",
    "submarino",
    "teleférico",
    "trenó",
    "charrete",
    "hoverboard",
    "foguete",
    "bicicleta tandem",
    "barco a vela",
    "trator",
    "skate",
    "patinete",
    "limusine",
    "monocicleta",

    // 💡 Coisas abstratas & divertidas
    "Wi-Fi caindo",
    "entrar em call errada",
    "perder o carregador",
    "fila do banco",
    "neura",
    "procrastinação",
    "ressaca",
    "tédio",
    "déjà vu",
    "soluço",
    "bater a cabeça na porta",
    "dormir em aula",
    "foto borrada",
    "bater o dedinho",
    "esquecimento",
    "ciúme",
    "sonambulismo",
    "torcicolo",

    // 🎪 Personagens fictícios & clássicos
    "Cinderela",
    "Pinóquio",
    "Peter Pan",
    "Chapeuzinho Vermelho",
    "Branca de Neve",
    "Alice no País das Maravilhas",
    "Polifemo",
    "Medusa",
    "Thor",
    "Batman",
    "Mulher-Maravilha",
    "Supergirl",

    // 🏆 Esportes
    "vôlei de praia",
    "surfe",
    "ginástica olímpica",
    "luta livre",
    "tiro com arco",
    "hipismo",
    "esgrima",
    "cabo de guerra",
    "corrida de saco",
    "tênis de mesa",
    "badminton",
];

export function getRandomWords(usedWords = [], n = 1) {
    const available = WORDS.filter((w) => !usedWords.includes(w));
    const shuffled = [...available].sort(() => Math.random() - 0.5);
    return shuffled.slice(0, n);
}
